// Shopping List
export const SHOPPING_LIST = {
    CREATE: 'CREATE',
    DELETE: 'DELETE',

    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    RENAME: 'RENAME',
    TOGGLE_STATE: 'TOGGLE_STATE',
};